---
- name: Install Packages
  become_user: root
  become: true
  apt:
    pkg: "{{ box.packages }}"
    state: latest
    update_cache: yes

- name: Upgrade system
  become_user: root
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: Generate locales
  become_user: root
  become: true
  command: locale-gen en_US en_US.UTF-8 uk_UA uk_UA.UTF-8

- name: Update locales
  become_user: root
  become: true
  command: update-locale

- name: SSH to /vagrant folder by default
  lineinfile:
    dest: /home/vagrant/.bashrc
    line: "cd {{ path.root }}"
    state: present
    insertafter: EOF

- name: Update timezone
  become_user: root
  become: true
  command: 'timedatectl set-timezone "{{ box.timezone }}"'

- name: Update date/time synchronization
  become_user: root
  become: true
  command: 'timedatectl set-ntp on'

- name: Restart NTP service
  become_user: root
  become: true
  service: name=ntp state=restarted
