---
- name: "Update PHP {{ php_version.version }} config"
  become_user: root
  become: true
  ini_file:
      dest: "/etc/php/{{ php_version.version }}/apache2/php.ini"
      section: PHP
      option: "{{ item.name }}"
      value: "{{ item.value }}"
  with_items:
    - { name: 'memory_limit', value: '{{ php.mem }}' }
    - { name: 'post_max_size', value: '200M' }
    - { name: 'upload_max_filesize', value: '200M' }
    - { name: 'display_errors', value: 'On' }
    - { name: 'error_reporting', value: 'E_ALL' }
    - { name: 'max_execution_time', value: '180' }

- name: "Update xdebug config for PHP {{ php_version.version }}"
  become_user: root
  become: true
  lineinfile:
      dest: "/etc/php/{{ php_version.version }}/mods-available/xdebug.ini"
      line: "{{ item }}"
  with_items:
    - 'xdebug.remote_enable="on"'
    - 'xdebug.remote_connect_back="on"'
    - 'xdebug.idekey="vagrant"'
    - 'xdebug.var_display_max_depth = -1'
    - 'xdebug.var_display_max_children = -1'
    - 'xdebug.var_display_max_data = -1'
