---
- name: "Install PHP {{ php_version.version }}"
  become_user: root
  become: true
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - "php{{ php_version.version }}"
    - "php{{ php_version.version }}-fpm"

- name: "Install PHP {{ php_version.version }} packages"
  become_user: root
  become: true
  apt:
    pkg: "php{{ php_version.version }}-{{ item }}"
    state: latest
    update_cache: yes
  with_items: "{{ php.version_packages }}"

- name: "Install PHP {{ php_version.version }} version-specific packages"
  become_user: root
  become: true
  apt:
    pkg: "php{{ php_version.version }}-{{ item }}"
    state: latest
    update_cache: yes
  with_items: "{{ php_version.packages }}"
