---
- name: Add PHP 5.6 repository
  become_user: root
  become: true
  apt_repository:
    repo: 'ppa:ondrej/php'
    state: present

- name: Install PHP 5.6
  become_user: root
  become: true
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - php5.6
    - php5.6-curl
    - php5.6-dom
    - php5.6-gd
    - php5.6-imap
    - php5.6-intl
    - php5.6-mcrypt
    - php5.6-mysql
    - php5.6-mbstring
    - php5.6-soap
    - php5.6-zip
    - libapache2-mod-php5.6

- name: Update PHP config
  become_user: root
  become: true
  ini_file: dest=/etc/php/5.6/apache2/php.ini section=PHP option={{ item.name }} value={{ item.value }}
  with_items:
    - { name: 'memory_limit', value: '{{ os.php.mem }}' }
    - { name: 'post_max_size', value: '200M' }
    - { name: 'upload_max_filesize', value: '200M' }
    - { name: 'display_errors', value: 'On' }
    - { name: 'error_reporting', value: 'E_ALL' }
    - { name: 'max_execution_time', value: '180' }
