---
- name: Use default MySQL credentials
  template:
    src: templates/tmp.cnf
    dest: ~/.my.cnf

- name: Update MySQL root password
  mysql_user: name=root host={{ item }} password={{ db.root_passwd }} state=present
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Use updated MySQL root credentials
  template:
    src: templates/wp.cnf
    dest: ~/.my.cnf
    owner: vagrant
    mode: 0600

- name: Restart MySQL server
  become_user: root
  become: true
  service: name=mysql state=restarted
