---
- name: Get Composer installer
  command: php -r "copy('https://getcomposer.org/installer', '/tmp/composer-setup.php');"

- name: Install Composer
  become_user: root
  become: true
  command: php /tmp/composer-setup.php --install-dir={{ path.bin }} --filename=composer

- name: Remove Composer installer
  command: php -r "unlink('/tmp/composer-setup.php');"
