---
- name: Get Composer installer
  command: php -r "copy('https://getcomposer.org/installer', '/tmp/composer-setup.php');"

# - name: Verify Composer installer
#   command: php -r "if (hash_file('SHA384', '/tmp/composer-setup.php') === '{{ composer_sha }}') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('/tmp/composer-setup.php'); } echo PHP_EOL;"

- name: Install Composer
  become_user: root
  become: true
  command: php /tmp/composer-setup.php --install-dir={{ path.bin }} --filename=composer

- name: Remove Composer installer
  command: php -r "unlink('/tmp/composer-setup.php');"
