---
- name: Additional aliases
  include_tasks: alias.yml
  with_items: "{{ path.aliases }}"

- name: Disable all PHP versions
  become_user: root
  become: true
  command: a2dismod {{ item }}
  with_items:
    - php5.6
    - php7.0
    # - php7.1
    # - php7.2

- name: Enable PHP{{ php.default }}
  become_user: root
  become: true
  command: a2enmod {{ item }}
  with_items:
    - "php{{ php.default }}"

- name: Restart Apache2 server
  become_user: root
  become: true
  service: name=apache2 state=restarted
