---
- name: Additional aliases
  include_tasks: alias.yml
  with_items: "{{ path.aliases }}"

# - name: Add aliases in Apache
#   become_user: root
#   become: true
#   template:
#     src: templates/alias.conf.j2
#     dest: "/etc/apache2/sites-available/aliases/{{ item }}.conf"
#     owner: root
#     mode: 0644
#   with_items: "{{ path.aliases }}"
#
# - name: Place PHP-Info file for http://{{ ansible_fqdn }}/info
#   template:
#     src: templates/info.php.j2
#     dest: "{{ dirs.base }}{{ dirs.web }}/info/index.php"
#
# - name: Place generic info file for http://{{ ansible_fqdn }}/box
#   template:
#     src: templates/box.php.j2
#     dest: "{{ dirs.base }}{{ dirs.web }}/box/index.php"

# - name: Place generic box info file
#   template:
#     src: templates/box.php.j2
#     dest: "{{ path.info }}/index.php"
#
- name: Disable all PHP versions
  become_user: root
  become: true
  command: a2dismod {{ item }}
  with_items:
    - php5.6
    - php7.0
    # - php7.1
    # - php7.2

- name: Enable PHP{{ os.php.ver }}
  become_user: root
  become: true
  command: a2enmod {{ item }}
  with_items:
    - "php{{ os.php.ver }}"

- name: Restart Apache2 server
  become_user: root
  become: true
  service: name=apache2 state=restarted
