---
- name: Install PHP
  become_user: root
  become: true
  apt: pkg={{ item }} state=latest
  with_items:
    - "php{{ os.php.ver }}"
    - "php{{ os.php.ver }}-curl"
    - "php{{ os.php.ver }}-dom"
    - "php{{ os.php.ver }}-gd"
    - "php{{ os.php.ver }}-imap"
    - "php{{ os.php.ver }}-intl"
    - "php{{ os.php.ver }}-mcrypt"
    - "php{{ os.php.ver }}-mysql"
    - "php{{ os.php.ver }}-mbstring"
    - "php{{ os.php.ver }}-zip"
    - "php{{ os.php.ver }}-soap"
    - php-imagick
    - php-gettext
    - php-xdebug
    - "libapache2-mod-php{{ os.php.ver }}"

- name: Update PHP config
  become_user: root
  become: true
  ini_file:
      dest: "/etc/php/{{ os.php.ver }}/apache2/php.ini"
      section: PHP
      option: "{{ item.name }}"
      value: "{{ item.value }}"
  with_items:
    - { name: 'memory_limit', value: '{{ os.php.mem }}' }
    - { name: 'post_max_size', value: '200M' }
    - { name: 'upload_max_filesize', value: '200M' }
    - { name: 'display_errors', value: 'On' }
    - { name: 'error_reporting', value: 'E_ALL' }
    - { name: 'max_execution_time', value: '180' }

- name: Update xdebug config
  become_user: root
  become: true
  lineinfile:
      dest: "/etc/php/{{ os.php.ver }}/mods-available/xdebug.ini"
      line: "{{ item }}"
  with_items:
    - 'xdebug.remote_enable="on"'
    - 'xdebug.remote_connect_back="on"'
    - 'xdebug.idekey="vagrant"'
    - 'xdebug.var_display_max_depth = -1'
    - 'xdebug.var_display_max_children = -1'
    - 'xdebug.var_display_max_data = -1'
