---
- name: Install MariaDB
  become_user: root
  become: true
  apt: pkg={{ item }} state=latest
  with_items:
    - mariadb-server
    - python-mysqldb

- name: Check to see if MySQL password already reset
  stat: path=~/.my.cnf
  register: mysql_myconf_file

- name: Update MySQL root password
  include_tasks: root_passwd.yml
  when: mysql_myconf_file.stat.exists is defined and mysql_myconf_file.stat.exists == false

- name: Create MySQL database for WordPress
  mysql_db:
    name: "{{ wp.db.name }}"
    state: present
  register: wp_db_created

- name: Create MySQL user for WordPress
  mysql_user:
      name: "{{ wp.db.user }}"
      password: "{{ wp.db.pass }}"
      host: "%"
      priv: "*.*:ALL,GRANT"
      state: present
