---
- name: Update MySQL root password
  become_user: root
  become: true
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ db.root_pass }}"
    state: present
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Change the auth plugin for the root user
  become_user: root
  become: true
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - update mysql.user set plugin = 'mysql_native_password' where User='root';

- name: Restart MySQL server
  become_user: root
  become: true
  service:
    name: mysql
    state: restarted

- name: Set MySQL default credentials
  template:
    src: templates/wp.cnf.j2
    dest: ~/.my.cnf
    owner: vagrant
    group: vagrant
    mode: 0600

- name: Remove anonymous users
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User=''

- name: Disallow root login remotely
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')

- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False
