---
- hosts: all
  become_user: root
  become_method: sudo
  vars_files:
    - ../conf.yml
    - vars.yml
  roles:
    - 10-server
    - 20-mysql
    - 25-mariadb
    - 30-apache2
    - 40-php
    - 50-composer
    - 60-phpMyAdmin
    - 70-wp-cli
    - 80-wordpress
    - 85-bedrock
    - 89-postinstall
