# Main configuration file. Settings could be ovewritten by the conf.yml
# in the project's root folder
---
# Host configuration
box:
  name: 'wp.wp' # domain name
  ip: '192.168.33.100'
  memsize: 2048
  cpus: 2
  sync: 'nfs'
  timezone: 'Europe/Kiev'
  packages:
    - aptitude
    - curl
    - gettext
    - git
    - mc
    - wget
    - zip
    - ntp
    # - npm
    # - nodejs-legacy

# Base directory names
dirs:
  base: '/vagrant' # base path on guest
  web: '/www' # directory for web stuff
  wp: '/wp' # WordPress directory

# Other paths
path:
  root: "{{ dirs.base }}"
  web: "{{ dirs.base }}{{ dirs.web }}"
  wp: "{{ dirs.base }}{{ dirs.web }}{{ dirs.wp }}"
  bin: "/usr/local/bin"
  log: "{{ dirs.base }}/log"
  phpmyadmin: "{{ dirs.base }}{{ dirs.web }}/my"
  aliases:
      - 'test'
      - 'info'
      - 'box'

# WordPress configuration
wp:
  version: latest # 'latest', 'nightly' or specific number (e.g. '4.8.1')
  bedrock: true # 'true' for Bedrock, 'false' for normal WordPress install
  title: 'New Project'
  langs: [] # for example: '[fr_FR, de_DE, es_ES]'
  user: # default user
    login: 'admin'
    pass: '1'
    email: 'a.bolgunovsky@codetiburon.com'
  db:
    name: 'wp'
    user: 'wp'
    pass: 'wp'
    prefix: 'wp_'
  uninstall:
    plugins: ['akismet', 'hello.php']
    themes: ['twentyfourteen', 'twentyfifteen', 'twentysixteen']
  install:
    plugins:
      - disable-emails
      - wp-mail-logging
      - https://github.com/wp-sync-db/wp-sync-db/archive/master.zip
      - https://github.com/wp-sync-db/wp-sync-db-media-files/archive/master.zip

# Database configuration
db:
  server: mariadb # 'mysql' or 'mariadb'
  root_pass: 'root'

# Ubuntu stuff
os:
  php:
    ver: 7.0
    mem: '512M'

# Other
verbous: true

# Additional domains
# hostmanager-aliases:
#   - singlesites.dev
#   - sample1.dev
#   - sample1.singlesites.dev
