# Main configuration file. Settings could be ovewritten by the conf.yml
# in the project's root folder
---
# Host configuration
box:
  name: 'wp.wp' # domain name
  ip: '192.168.33.100'
  memsize: 2048
  cpus: 2
  sync: 'nfs'
  timezone: 'Europe/Kiev'
  packages:
    - aptitude
    - curl
    - gettext
    - git
    - ntp
    - mc
    - wget
    - zip

# Base directory names
dirs:
  base: '/vagrant' # base path on guest
  web: '/www' # directory for web stuff
  wp: '/wp' # WordPress directory

# Other paths
path:
  root: "{{ dirs.base }}"
  web: "{{ dirs.base }}{{ dirs.web }}"
  wp: "{{ dirs.base }}{{ dirs.web }}{{ dirs.wp }}"
  bin: "/usr/local/bin"
  log: "{{ dirs.base }}/log"
  phpmyadmin: "{{ dirs.base }}{{ dirs.web }}/my"
  aliases:
      - 'test'
      - 'info'
      - 'box'

# WordPress configuration
wp:
  version: latest # 'latest', 'nightly' or specific number (e.g. '4.8.1')
  bedrock: true # 'true' for Bedrock, 'false' for normal WordPress install
  title: 'New Project'
  langs: [] # for example: '[fr_FR, de_DE, es_ES]'
  user: # default user
    login: 'admin'
    pass: '1'
    email: 'balexey88@gmail.com'
  db:
    name: 'wp'
    user: 'wp'
    pass: 'wp'
    prefix: 'wp_'
  uninstall:
    plugins: ['akismet', 'hello.php']
    themes: ['twentyfourteen', 'twentyfifteen', 'twentysixteen']
  install:
    plugins:
      - disable-emails
      - wp-mail-logging

# Database configuration
db:
  server: MariaDB # 'MySQL' or 'MariaDB'

# PHP configuration
php:
  default: 7.2
  mem: '512M'
  versions:
    -
      version: 5.6
      packages:
        - xml
        - mcrypt
    -
      version: 7.0
      packages:
        - mcrypt
    -
      version: 7.1
      packages:
        - mcrypt
    -
      version: 7.2
      packages: []
  version_packages:
    - curl
    - dom
    - gd
    - imap
    - intl
    - mysql
    - mbstring
    - soap
    - sqlite3
    - zip
  packages:
    - imagick
    - gettext
    - xdebug

# Additional domains
# hostmanager-aliases:
#   - site.wp.wp
#   - wp2.wp

# Other
verbose: true
