---
- name: Additional dirs
  file:
      path: "{{ item }}"
      state: directory
  with_items:
    - "{{ path.wp }}"

- name: Check if WordPress is present
  stat: "path={{ path.wp }}/wp-load.php"
  register: wp_load_file

- name: Download WordPress
  command: wp core download --version='{{ wp.version }}'
  when: wp_load_file.stat.exists is defined and wp_load_file.stat.exists == false

- name: Configure WordPress
  command: wp core config --dbname={{ wp.db.name }} --dbuser={{ wp.db.user }} --dbpass={{ wp.db.pass }} --dbprefix={{ wp.db.prefix }} --force
